openapi: 3.0.0 
info: 
  description: This is a safe password API
  version: 1.0.0
  title: Safe Password API
  license:
    name: Apache-2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
tags: 
  - name: Password
    description: Generate and validate safe passwords using AI and regular expression

servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /validate:
    post:
      tags:
        - Regular expression Password
      description: Validate a password with a regular expression
      operationId: validate
      summary: Validate a password with a regular expression
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  description: The password to validate
                  example: "password123"
      responses:
        '200':
          description: A valid password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PasswordResponse'

        '422':
          description: Invalid password.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PasswordResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /ai/generate:
    get:
      tags:
        - AI Password
      description: Generate a safe password using AI
      operationId: generate
      summary: Generate a safe password using AI
      responses:
        '200':
          description: A safe password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PasswordResponse'
        '422':
          description: Invalid password.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PasswordResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /ai/validate:
    post:
      tags:
        - AI Password
      description: Validate a password using AI
      operationId: validate
      summary: Validate a password using AI
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  description: The password to validate
                  example: "password123"
      responses:
        '200':
          description: A valid password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PasswordResponse'
        '422':
          description: Invalid password.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PasswordResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    PasswordResponse:
      type: object
      properties:
        password:
          type: string
          description: The password
        status:
          type: string
          description: The status of the response
          enum:
            - VALID
            - INVALID
            - ERROR
        message:
          type: string
          description: The message of the response
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: The message of the response